/* Generated By:JavaCC: Do not edit this line. MooplParser.java */
  import syntaxtree.*;
  import java.util.List;
  import java.util.ArrayList;
  import java.util.LinkedList;
  public class MooplParser implements MooplParserConstants {

  final public void testTokens() throws ParseException {
  Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
      case FUN:
      case CLASS:
      case INT:
      case NEW:
      case SELF:
      case RETURN:
      case EXTENDS:
      case LOCAL:
      case BOOLEAN:
      case OUTPUT:
      case WHILE:
      case DO:
      case IF:
      case ELSE:
      case THEN:
      case TRUE:
      case FALSE:
      case LENGTH:
      case ISNULL:
      case LBRACKET:
      case RBRACKET:
      case L_SQR_BRACKET:
      case R_SQR_BRACKET:
      case LPAREN:
      case RPAREN:
      case PERIOD:
      case SEMICOLON:
      case COMMA:
      case INTEGER_LITERAL:
      case NOT:
      case LOG_AND:
      case LESS_THAN:
      case EQUAL_TO:
      case ASSIGN_OP:
      case DIV:
      case ADD:
      case SUBT:
      case MULT:
      case ID:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
      case FUN:
      case CLASS:
      case INT:
      case NEW:
      case SELF:
      case RETURN:
      case EXTENDS:
      case LOCAL:
      case BOOLEAN:
      case OUTPUT:
      case WHILE:
      case DO:
      case IF:
      case ELSE:
      case THEN:
      case TRUE:
      case FALSE:
      case LENGTH:
      case ISNULL:
      case LBRACKET:
      case RBRACKET:
      case L_SQR_BRACKET:
      case R_SQR_BRACKET:
      case LPAREN:
      case RPAREN:
      case PERIOD:
      case SEMICOLON:
      case COMMA:
      case NOT:
      case LOG_AND:
      case LESS_THAN:
      case EQUAL_TO:
      case ASSIGN_OP:
      case DIV:
      case ADD:
      case SUBT:
      case MULT:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROC:
          t = jj_consume_token(PROC);
          break;
        case FUN:
          t = jj_consume_token(FUN);
          break;
        case CLASS:
          t = jj_consume_token(CLASS);
          break;
        case INT:
          t = jj_consume_token(INT);
          break;
        case NEW:
          t = jj_consume_token(NEW);
          break;
        case SELF:
          t = jj_consume_token(SELF);
          break;
        case RETURN:
          t = jj_consume_token(RETURN);
          break;
        case EXTENDS:
          t = jj_consume_token(EXTENDS);
          break;
        case LOCAL:
          t = jj_consume_token(LOCAL);
          break;
        case BOOLEAN:
          t = jj_consume_token(BOOLEAN);
          break;
        case OUTPUT:
          t = jj_consume_token(OUTPUT);
          break;
        case WHILE:
          t = jj_consume_token(WHILE);
          break;
        case DO:
          t = jj_consume_token(DO);
          break;
        case IF:
          t = jj_consume_token(IF);
          break;
        case ELSE:
          t = jj_consume_token(ELSE);
          break;
        case THEN:
          t = jj_consume_token(THEN);
          break;
        case TRUE:
          t = jj_consume_token(TRUE);
          break;
        case FALSE:
          t = jj_consume_token(FALSE);
          break;
        case LENGTH:
          t = jj_consume_token(LENGTH);
          break;
        case ISNULL:
          t = jj_consume_token(ISNULL);
          break;
        case LBRACKET:
          t = jj_consume_token(LBRACKET);
          break;
        case RBRACKET:
          t = jj_consume_token(RBRACKET);
          break;
        case L_SQR_BRACKET:
          t = jj_consume_token(L_SQR_BRACKET);
          break;
        case R_SQR_BRACKET:
          t = jj_consume_token(R_SQR_BRACKET);
          break;
        case LPAREN:
          t = jj_consume_token(LPAREN);
          break;
        case RPAREN:
          t = jj_consume_token(RPAREN);
          break;
        case PERIOD:
          t = jj_consume_token(PERIOD);
          break;
        case SEMICOLON:
          t = jj_consume_token(SEMICOLON);
          break;
        case COMMA:
          t = jj_consume_token(COMMA);
          break;
        case NOT:
          t = jj_consume_token(NOT);
          break;
        case LOG_AND:
          t = jj_consume_token(LOG_AND);
          break;
        case LESS_THAN:
          t = jj_consume_token(LESS_THAN);
          break;
        case EQUAL_TO:
          t = jj_consume_token(EQUAL_TO);
          break;
        case ASSIGN_OP:
          t = jj_consume_token(ASSIGN_OP);
          break;
        case DIV:
          t = jj_consume_token(DIV);
          break;
        case ADD:
          t = jj_consume_token(ADD);
          break;
        case SUBT:
          t = jj_consume_token(SUBT);
          break;
        case MULT:
          t = jj_consume_token(MULT);
          break;
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        System.out.println("Recognised as valid token: " + t.image);
        break;
      case INTEGER_LITERAL:
        t = jj_consume_token(INTEGER_LITERAL);
        System.out.println("Recognised as INTEGER_LITERAL: " + t.image);
        break;
      case ID:
        t = jj_consume_token(ID);
        System.out.println("Recognised as ID: " + t.image);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
  }

  final public Program nt_Program() throws ParseException {
ProcDecl pds;
ClassDecl cds;
List<ProcDecl> pdl = new LinkedList<ProcDecl>();
List<ClassDecl> cdl = new LinkedList<ClassDecl>();
    label_2:
    while (true) {
      pds = nt_ProcDecl();
                   pdl.add(pds);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      cds = nt_ClassDecl();
                                                          cdl.add(cds);
    }
    jj_consume_token(0);
  {if (true) return new Program(pdl, cdl);}
    throw new Error("Missing return statement in function");
  }

  final public ClassDecl nt_ClassDecl() throws ParseException {
Token t, t2;
FieldDecl fds;
MethodDecl mds;
List<FieldDecl> fdl = new LinkedList<FieldDecl>();
List<MethodDecl> mdl = new LinkedList<MethodDecl>();
    jj_consume_token(CLASS);
    t = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      jj_consume_token(LBRACKET);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case BOOLEAN:
        case ID:
          ;
          break;
        default:
          jj_la1[5] = jj_gen;
          break label_4;
        }
        fds = nt_FieldDecl();
                                     fdl.add(fds);
      }
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROC:
        case FUN:
          ;
          break;
        default:
          jj_la1[6] = jj_gen;
          break label_5;
        }
        mds = nt_MethodDecl();
                                                                           mdl.add(mds);
      }
      jj_consume_token(RBRACKET);
                                                                                                         {if (true) return new ClassDecl(t.image, fdl, mdl);}
      break;
    case EXTENDS:
      jj_consume_token(EXTENDS);
      t2 = jj_consume_token(ID);
      jj_consume_token(LBRACKET);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case BOOLEAN:
        case ID:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_6;
        }
        fds = nt_FieldDecl();
                                                         fdl.add(fds);
      }
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROC:
        case FUN:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_7;
        }
        mds = nt_MethodDecl();
                                                                                               mdl.add(mds);
      }
      jj_consume_token(RBRACKET);
                                                                                                                             {if (true) return new ClassDeclExtends(t.image, t2.image, fdl, mdl);}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public FieldDecl nt_FieldDecl() throws ParseException {
Type t;
Token t1;
    t = nt_Type();
    t1 = jj_consume_token(ID);
    jj_consume_token(SEMICOLON);
                                    {if (true) return new FieldDecl(t, t1.image);}
    throw new Error("Missing return statement in function");
  }

  final public MethodDecl nt_MethodDecl() throws ParseException {
MethodDecl mds;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PROC:
      mds = nt_ProcDecl();
      break;
    case FUN:
      mds = nt_FunDecl();
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return mds;}
    throw new Error("Missing return statement in function");
  }

  final public ProcDecl nt_ProcDecl() throws ParseException {
Token t1;
List<Formal> fml;
List<Stm> stl = new LinkedList<Stm>();
Stm st;
    jj_consume_token(PROC);
    t1 = jj_consume_token(ID);
    jj_consume_token(LPAREN);
    fml = nt_FormalList();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACKET);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NEW:
      case SELF:
      case LOCAL:
      case OUTPUT:
      case WHILE:
      case IF:
      case TRUE:
      case FALSE:
      case ISNULL:
      case LBRACKET:
      case LPAREN:
      case INTEGER_LITERAL:
      case NOT:
      case ID:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_8;
      }
      st = nt_Statement();
                                                                                     stl.add(st);
    }
    jj_consume_token(RBRACKET);
    {if (true) return new ProcDecl(t1.image, fml, stl);}
    throw new Error("Missing return statement in function");
  }

  final public FunDecl nt_FunDecl() throws ParseException {
Type t;
Token t1;
List<Formal> fml;
List<Stm> stl = new LinkedList<Stm>();
Stm st;
Exp ex;
    jj_consume_token(FUN);
    t = nt_Type();
    t1 = jj_consume_token(ID);
    jj_consume_token(LPAREN);
    fml = nt_FormalList();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACKET);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NEW:
      case SELF:
      case LOCAL:
      case OUTPUT:
      case WHILE:
      case IF:
      case TRUE:
      case FALSE:
      case ISNULL:
      case LBRACKET:
      case LPAREN:
      case INTEGER_LITERAL:
      case NOT:
      case ID:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_9;
      }
      st = nt_Statement();
                                 stl.add(st);
    }
    jj_consume_token(RETURN);
    ex = nt_Exp();
    jj_consume_token(SEMICOLON);
    jj_consume_token(RBRACKET);
   {if (true) return new FunDecl(t, t1.image, fml, stl, ex);}
    throw new Error("Missing return statement in function");
  }

  final public List<Formal> nt_FormalList() throws ParseException {
Type t;
Token t1;
List<Formal> fml = new LinkedList<Formal>();
Formal fm;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOLEAN:
    case ID:
      t = nt_Type();
      t1 = jj_consume_token(ID);
                         fml.add(new Formal(t, t1.image));
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_10;
        }
        fm = nt_FormalRest();
                                                                                fml.add(fm);
      }
      break;
    default:
      jj_la1[14] = jj_gen;
       {if (true) return fml;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Formal nt_FormalRest() throws ParseException {
Type t;
Token t1;
    jj_consume_token(COMMA);
    t = nt_Type();
    t1 = jj_consume_token(ID);
                               {if (true) return new Formal(t, t1.image);}
    throw new Error("Missing return statement in function");
  }

  final public Type nt_Type() throws ParseException {
Type t;
Token t1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
      t1 = jj_consume_token(BOOLEAN);
                   t=new TypeBoolean();
      break;
    case INT:
      t1 = jj_consume_token(INT);
               t=new TypeInt();
      break;
    case ID:
      t1 = jj_consume_token(ID);
              t=new TypeClassType(t1.image);
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_11:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_11;
      }
      jj_consume_token(L_SQR_BRACKET);
      jj_consume_token(R_SQR_BRACKET);
                                                 t=new TypeArray(t);
    }
      {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  final public Stm nt_Statement() throws ParseException {
Type t;
Token t1;
Var var;
Exp ex1, ex2, expe;
List<Exp> exl;
Stm bl1, bl2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      bl1 = nt_Block();
                     {if (true) return bl1;}
      break;
    case LOCAL:
      jj_consume_token(LOCAL);
      t = nt_Type();
      t1 = jj_consume_token(ID);
      jj_consume_token(SEMICOLON);
                                              {if (true) return new StmVarDecl(t, t1.image);}
      break;
    default:
      jj_la1[17] = jj_gen;
      if (jj_2_2(2)) {
        var = nt_Var();
        jj_consume_token(ASSIGN_OP);
        ex1 = nt_Exp();
        jj_consume_token(SEMICOLON);
                                                                     {if (true) return new StmAssign(var, ex1);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NEW:
        case SELF:
        case TRUE:
        case FALSE:
        case ISNULL:
        case LPAREN:
        case INTEGER_LITERAL:
        case NOT:
        case ID:
          expe = nt_PrimaryExp();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case L_SQR_BRACKET:
            jj_consume_token(L_SQR_BRACKET);
            ex1 = nt_Exp();
            jj_consume_token(R_SQR_BRACKET);
            jj_consume_token(ASSIGN_OP);
            ex2 = nt_Exp();
            jj_consume_token(SEMICOLON);
                                                                                          {if (true) return new StmArrayAssign(expe, ex1, ex2);}
            break;
          case PERIOD:
            jj_consume_token(PERIOD);
            t1 = jj_consume_token(ID);
            jj_consume_token(LPAREN);
            exl = nt_ExpList();
            jj_consume_token(RPAREN);
            jj_consume_token(SEMICOLON);
                                                                        {if (true) return new StmCall(expe, t1.image, exl);}
            break;
          default:
            jj_la1[16] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        case IF:
          jj_consume_token(IF);
          jj_consume_token(LPAREN);
          ex1 = nt_Exp();
          jj_consume_token(RPAREN);
          jj_consume_token(THEN);
          bl1 = nt_Statement();
          jj_consume_token(ELSE);
          bl2 = nt_Statement();
                                                                                             {if (true) return new StmIf(ex1, bl1, bl2);}
          break;
        case WHILE:
          jj_consume_token(WHILE);
          jj_consume_token(LPAREN);
          ex1 = nt_Exp();
          jj_consume_token(RPAREN);
          jj_consume_token(DO);
          bl1 = nt_Statement();
                                                                     {if (true) return new StmWhile(ex1, bl1);}
          break;
        case OUTPUT:
          jj_consume_token(OUTPUT);
          ex1 = nt_Exp();
          jj_consume_token(SEMICOLON);
                                       {if (true) return new StmOutput(ex1);}
          break;
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public StmBlock nt_Block() throws ParseException {
List<Stm> stl = new LinkedList<Stm>();
Stm stm;
    jj_consume_token(LBRACKET);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NEW:
      case SELF:
      case LOCAL:
      case OUTPUT:
      case WHILE:
      case IF:
      case TRUE:
      case FALSE:
      case ISNULL:
      case LBRACKET:
      case LPAREN:
      case INTEGER_LITERAL:
      case NOT:
      case ID:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_12;
      }
      stm = nt_Statement();
                                  stl.add(stm);
    }
    jj_consume_token(RBRACKET);
                                                                {if (true) return new StmBlock(stl);}
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_Exp() throws ParseException {
Token t1;
ExpOp.Op op;
Exp ex1, ex2, ex3;
List<Exp> exl;
    ex1 = nt_PrimaryExp();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LOG_AND:
    case LESS_THAN:
    case EQUAL_TO:
    case DIV:
    case ADD:
    case SUBT:
    case MULT:
      op = nt_Op();
      ex2 = nt_PrimaryExp();
                                     {if (true) return new ExpOp(ex1, op, ex2);}
      break;
    case L_SQR_BRACKET:
      jj_consume_token(L_SQR_BRACKET);
      ex3 = nt_Exp();
      jj_consume_token(R_SQR_BRACKET);
                                                   {if (true) return new ExpArrayLookup(ex1, ex3);}
      break;
    case PERIOD:
      jj_consume_token(PERIOD);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LENGTH:
        jj_consume_token(LENGTH);
               {if (true) return new ExpArrayLength(ex1);}
        break;
      case ID:
        t1 = jj_consume_token(ID);
        jj_consume_token(LPAREN);
        exl = nt_ExpList();
        jj_consume_token(RPAREN);
                                                   {if (true) return new ExpCall(ex1, t1.image, exl);}
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[21] = jj_gen;
        {if (true) return ex1;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_PrimaryExp() throws ParseException {
Exp ex1, ex2;
Type t;
Token t1;
Var var;
List<Exp> exl = new LinkedList<Exp>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      t1 = jj_consume_token(INTEGER_LITERAL);
                            {if (true) return new ExpInteger(Integer.parseInt(t1.image));}
      break;
    case TRUE:
      jj_consume_token(TRUE);
             {if (true) return new ExpTrue();}
      break;
    case FALSE:
      jj_consume_token(FALSE);
              {if (true) return new ExpFalse();}
      break;
    case ID:
      var = nt_Var();
                   {if (true) return new ExpVar(var);}
      break;
    case SELF:
      jj_consume_token(SELF);
             {if (true) return new ExpSelf();}
      break;
    default:
      jj_la1[22] = jj_gen;
      if (jj_2_3(3)) {
        jj_consume_token(NEW);
        t1 = jj_consume_token(ID);
        jj_consume_token(LPAREN);
        exl = nt_ExpList();
        jj_consume_token(RPAREN);
                                                                    {if (true) return new ExpNewObject(t1.image, exl);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NEW:
          jj_consume_token(NEW);
          t = nt_Type();
          jj_consume_token(L_SQR_BRACKET);
          ex1 = nt_Exp();
          jj_consume_token(R_SQR_BRACKET);
                                                                     {if (true) return new ExpNewArray(t, ex1);}
          break;
        case NOT:
          jj_consume_token(NOT);
          ex2 = nt_PrimaryExp();
                               {if (true) return new ExpNot(ex2);}
          break;
        case ISNULL:
          jj_consume_token(ISNULL);
          ex2 = nt_PrimaryExp();
                                   {if (true) return new ExpIsnull(ex2);}
          break;
        case LPAREN:
          jj_consume_token(LPAREN);
          ex1 = nt_Exp();
          jj_consume_token(RPAREN);
                                     {if (true) return ex1;}
          break;
        default:
          jj_la1[23] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Var nt_Var() throws ParseException {
Token t1;
    t1 = jj_consume_token(ID);
    {if (true) return new Var(t1.image);}
    throw new Error("Missing return statement in function");
  }

  final public List<Exp> nt_ExpList() throws ParseException {
Exp ex1;
List<Exp> exl = new LinkedList<Exp>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NEW:
    case SELF:
    case TRUE:
    case FALSE:
    case ISNULL:
    case LPAREN:
    case INTEGER_LITERAL:
    case NOT:
    case ID:
      ex1 = nt_Exp();
                  exl.add(ex1);
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[24] = jj_gen;
          break label_13;
        }
        ex1 = nt_ExpRest();
                                                     exl.add(ex1);
      }
      {if (true) return exl;}
      break;
    default:
      jj_la1[25] = jj_gen;
      {if (true) return exl;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_ExpRest() throws ParseException {
Exp ex1;
    jj_consume_token(COMMA);
    ex1 = nt_Exp();
                         {if (true) return ex1;}
    throw new Error("Missing return statement in function");
  }

  final public ExpOp.Op nt_Op() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LOG_AND:
      jj_consume_token(LOG_AND);
               {if (true) return ExpOp.Op.AND;}
      break;
    case LESS_THAN:
      jj_consume_token(LESS_THAN);
                 {if (true) return ExpOp.Op.LESSTHAN;}
      break;
    case EQUAL_TO:
      jj_consume_token(EQUAL_TO);
                {if (true) return ExpOp.Op.EQUALS;}
      break;
    case DIV:
      jj_consume_token(DIV);
           {if (true) return ExpOp.Op.DIV;}
      break;
    case ADD:
      jj_consume_token(ADD);
           {if (true) return ExpOp.Op.PLUS;}
      break;
    case SUBT:
      jj_consume_token(SUBT);
            {if (true) return ExpOp.Op.MINUS;}
      break;
    case MULT:
      jj_consume_token(MULT);
            {if (true) return ExpOp.Op.TIMES;}
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_3_2() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(ASSIGN_OP)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(L_SQR_BRACKET)) return true;
    if (jj_scan_token(R_SQR_BRACKET)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MooplParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffffff00,0xffffff00,0xffffff00,0x100,0x400,0x20800,0x300,0x20800,0x300,0x10008000,0x300,0x1b2d3000,0x1b2d3000,0x0,0x20800,0x20800,0x40000000,0x10010000,0xb2c3000,0x1b2d3000,0x4000000,0x40000000,0x3002000,0x8001000,0x0,0xb003000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xffff,0x7fdf,0xffff,0x0,0x0,0x8000,0x0,0x8000,0x0,0x0,0x0,0x8061,0x8061,0x10,0x8000,0x8000,0x4,0x0,0x8061,0x8061,0x8000,0x7b84,0x8020,0x41,0x10,0x8061,0x7b80,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[3];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MooplParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MooplParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MooplParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MooplParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MooplParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MooplParser(MooplParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MooplParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[48];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 27; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 48; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

  }
